window.PinyinShooterGame = window.PinyinShooterGame || {};

PinyinShooterGame.Data = {
    characters: [
        { char: '猫', pinyin: 'māo', tone: 1, emoji: '🐱' },
        { char: '狗', pinyin: 'gǒu', tone: 3, emoji: '🐶' },
        { char: '书', pinyin: 'shū', tone: 1, emoji: '📖' },
        { char: '笔', pinyin: 'bǐ', tone: 3, emoji: '✏️' },
        { char: '水', pinyin: 'shuǐ', tone: 3, emoji: '💧' },
        { char: '火', pinyin: 'huǒ', tone: 3, emoji: '🔥' },
        { char: '山', pinyin: 'shān', tone: 1, emoji: '⛰️' },
        { char: '人', pinyin: 'rén', tone: 2, emoji: '🧑' },
        { char: '天', pinyin: 'tiān', tone: 1, emoji: '☀️' },
        { char: '地', pinyin: 'dì', tone: 4, emoji: '🌍' },
        { char: '月', pinyin: 'yuè', tone: 4, emoji: '🌙' },
        { char: '日', pinyin: 'rì', tone: 4, emoji: '☀️' },
        { char: '星', pinyin: 'xīng', tone: 1, emoji: '⭐' },
        { char: '云', pinyin: 'yún', tone: 2, emoji: '☁️' },
        { char: '风', pinyin: 'fēng', tone: 1, emoji: '🌬️' },
        { char: '雨', pinyin: 'yǔ', tone: 3, emoji: '🌧️' },
        { char: '电', pinyin: 'diàn', tone: 4, emoji: '⚡' },
        { char: '花', pinyin: 'huā', tone: 1, emoji: '🌸' },
        { char: '草', pinyin: 'cǎo', tone: 3, emoji: '🌿' },
        { char: '树', pinyin: 'shù', tone: 4, emoji: '🌳' },
        { char: '鸟', pinyin: 'niǎo', tone: 3, emoji: '🐦' },
        { char: '鱼', pinyin: 'yú', tone: 2, emoji: '🐟' },
        { char: '马', pinyin: 'mǎ', tone: 3, emoji: '🐎' },
        { char: '牛', pinyin: 'niú', tone: 2, emoji: '🐂' },
        { char: '羊', pinyin: 'yáng', tone: 2, emoji: '🐑' },
        { char: '左', pinyin: 'zuǒ', tone: 3, emoji: '👈' },
        { char: '右', pinyin: 'yòu', tone: 4, emoji: '👉' },
        { char: '大', pinyin: 'dà', tone: 4, emoji: '🐘' },
        { char: '小', pinyin: 'xiǎo', tone: 3, emoji: '🐭' },
        { char: '车', pinyin: 'chē', tone: 1, emoji: '🚗' },
        { char: '船', pinyin: 'chuán', tone: 2, emoji: '🚢' },
        { char: '门', pinyin: 'mén', tone: 2, emoji: '🚪' },
        { char: '刀', pinyin: 'dāo', tone: 1, emoji: '🔪' },
        { char: '衣', pinyin: 'yī', tone: 1, emoji: '👕' },
        { char: '食', pinyin: 'shí', tone: 2, emoji: '🍔' },
        { char: '住', pinyin: 'zhù', tone: 4, emoji: '🏠' },
        { char: '行', pinyin: 'xíng', tone: 2, emoji: '🚶' },
        { char: '手', pinyin: 'shǒu', tone: 3, emoji: '✋' },
        { char: '足', pinyin: 'zú', tone: 2, emoji: '🦶' },
        { char: '头', pinyin: 'tóu', tone: 2, emoji: '👤' },
        { char: '心', pinyin: 'xīn', tone: 1, emoji: '❤️' },
        { char: '眼', pinyin: 'yǎn', tone: 3, emoji: '👀' },
        { char: '耳', pinyin: 'ěr', tone: 3, emoji: '👂' },
        { char: '口', pinyin: 'kǒu', tone: 3, emoji: '👄' },
        { char: '鼻', pinyin: 'bí', tone: 2, emoji: '👃' },
        { char: '笑', pinyin: 'xiào', tone: 4, emoji: '😄' },
        { char: '哭', pinyin: 'kū', tone: 1, emoji: '😭' },
        { char: '爱', pinyin: 'ài', tone: 4, emoji: '❤️' },
        { char: '钱', pinyin: 'qián', tone: 2, emoji: '💰' },
        { char: '球', pinyin: 'qiú', tone: 2, emoji: '⚽' },
        { char: '灯', pinyin: 'dēng', tone: 1, emoji: '💡' },
        { char: '画', pinyin: 'huà', tone: 4, emoji: '🖼️' },
        { char: '唱', pinyin: 'chàng', tone: 4, emoji: '🎤' },
        { char: '跳', pinyin: 'tiào', tone: 4, emoji: '💃' },
        { char: '跑', pinyin: 'pǎo', tone: 3, emoji: '🏃' },
        { char: '飞', pinyin: 'fēi', tone: 1, emoji: '✈️' },
        { char: '坐', pinyin: 'zuò', tone: 4, emoji: '🪑' },
        { char: '站', pinyin: 'zhàn', tone: 4, emoji: '🧍' }
    ]
}; 